version: '3.8'

services:
  matter-server:
    container_name: matter-server
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    privileged: true
    cap_add:
      - ALL
    security_opt:
      - apparmor=unconfined
    volumes:
      - /mnt/data/udobnidom/matter-server/data:/data
      - /run/dbus:/run/dbus:ro
    network_mode: host
